name: Deploy to ECR
on:
 
  push:
 
    branches: [ main ]
env:
 
  ECR_REPOSITORY: eksgithubactions
 
  EKS_CLUSTER_NAME: ekscluster
 
  AWS_REGION: ap-southeast-1
jobs:
 
  build:
 
    name: Deployment
 
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
 
      id: commit
 
      uses: prompt/actions-commit-hash@v2
    - name: Check out code
 
      uses: actions/checkout@v2
 
    - name: Set up JDK 17
 
      uses: actions/setup-java@v4
 
      with:
 
        java-version: '17'
 
        distribution: 'temurin'
 
        cache: maven
 
    - name: Build with Maven
 
      run: mvn -B package --file pom.xml
 
    - name: Configure AWS credentials
 
      uses: aws-actions/configure-aws-credentials@v1
 
      with:
 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
        aws-region: ${{env.AWS_REGION}}
    - name: Login to Amazon ECR
 
      id: login-ecr
 
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
 
      env:
 
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}        
 
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
 
      run: |
 
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f Dockerfile .
 
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
